#!/bin/bash
############### Server ###############
#            Run as app user         #
######################################

echo "Which app?"
echo -e "\n"
read app
echo -e "\n"

user=$app
base="/var/www"
src="/var/opt/git/odoo"
script=$src"/VAR/oo-adds/upper"
server=$base/$app"/srv"
adds=$base/$app"/adds/"
themes=$base/$app"/themes"
backup=$base/$app"/bu"
data=$base/$app"/.local"
etc=$script"/etc/"
dirs=$server,$backup,$adds,$data,$themes,$etc

echo "Backup & update database, which database?: "
echo -e "\n"
read db
echo -e "\n"

if [ "$db" != "" ]; then
  echo "$db is going to be saved..."
  echo -e "\n"
  sleep 2
  now=$(date +"%Y-%m-%d_%H-%M-%S")
  filename="DB__$db.$now.gz"
  db_bup_file=$backup"/"$filename
  pg_dump $db | gzip -c > $db_bup_file
  echo "Backup of db can be founded here: $db_bup_file..."
  echo -e "\n"
else
  echo "No backup has been made."
fi

echo -e "\n"
echo "Changing the path..."
echo -e "\n"
sleep 1

if [ "$db" != "" ]; then
  echo "$db is going to be updated..."
  sleep 1
  echo -e "\n"
  echo "Going to update $db "
  sleep 1
  echo -e "\n"
  cd $server
  ./odoo.py --update=all --workers=0 --no-xmlrpc --stop-after-init --database=$db --addons-path=$server/addons,$base/$app/adds
else
  echo "Nothing backuped!"
  sleep 1
  echo -e "\n"
fi

echo "Finished! All Done."